web:
  build: node
  working_dir: /usr/src/app
  volumes:
    - .:/usr/src/app
  links:
    - db
  ports:
    - "1337:1337"
  command: node app.js
db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: test
  ports:
    - "3306:3306"
phpmyadmin:
  image: efynox/apache2-php
  command: apache2ctl -D FOREGROUND
  links:
    - db
  ports:
    - "80:80"
